name: Deploy Website
on:
  push:
    branches: [ main ]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check AWS CLI
        run: 
          aws --version
      - name: Run a multi-line script
        run: |
          echo "Our First github deployment"
